name: Bug Report
description: Report a bug in SolidityGuard
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Scanner / Pattern Detection
        - Web App (solidityguard.org)
        - Desktop App (Tauri)
        - CLI
        - Report Generator
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Upload contract X
        2. Run scan with tools Y
        3. See error Z

  - type: textarea
    id: contract
    attributes:
      label: Contract Code (if applicable)
      description: Minimal Solidity code that triggers the bug
      render: solidity

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - False Positive (flagged as vulnerable but is safe)
        - False Negative (missed a real vulnerability)
        - Crash / Error
        - Incorrect Severity
        - UI/UX Issue
        - Other

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "v1.0.0 or commit hash"
