name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe what you'd like to see.

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Vulnerability Pattern
        - Tool Integration
        - Scanner Improvement
        - Report Format
        - Web App Feature
        - Desktop App Feature
        - CLI Feature
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this be useful? What problem does it solve?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered alternative approaches?
