import { Link } from 'react-router'
import { ArrowLeft, Shield } from 'lucide-react'

export default function Privacy() {
  return (
    <div className="min-h-screen bg-bg-primary p-6">
    <div className="max-w-3xl mx-auto">
      <div className="flex items-center justify-between mb-4">
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 text-[12px] text-text-secondary hover:text-text-primary transition-colors no-underline"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          Back to SolidityGuard
        </Link>
        <Link to="/" className="inline-flex items-center gap-2 text-[14px] font-semibold text-text-primary no-underline">
          <Shield className="w-4 h-4 text-accent" />
          SolidityGuard
        </Link>
      </div>

      <h1 className="text-[20px] font-bold text-text-primary tracking-tight mb-1">
        Privacy Policy
      </h1>
      <p className="text-[13px] text-text-secondary mb-6">
        Last updated: February 10, 2026
      </p>

      <div className="glass rounded-xl p-6 space-y-6 text-[13px] text-text-secondary leading-relaxed">
        <section>
          <h2 className="text-[15px] font-semibold text-text-primary mb-2">1. Introduction</h2>
          <p>
            Alt Research Ltd. (&quot;Company&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) operates
            SolidityGuard (the &quot;Service&quot;). This Privacy Policy explains how we collect, use, and
            protect your information when you use our Service.
          </p>
        </section>

        <section>
          <h2 className="text-[15px] font-semibold text-text-primary mb-2">2. Data We Collect</h2>

          <h3 className="text-[13px] font-semibold text-text-primary mt-3 mb-1">2.1 Account Information</h3>
          <p>
            When you sign in via Google OAuth, we receive and store the following information from your
            Google account:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>Name</li>
            <li>Email address</li>
            <li>Profile picture URL</li>
          </ul>
          <p className="mt-2">
            We use this information solely for authentication and displaying your profile within the Service.
            We do not access your Google Drive, Gmail, contacts, or any other Google services.
          </p>

          <h3 className="text-[13px] font-semibold text-text-primary mt-3 mb-1">2.2 Uploaded Smart Contracts</h3>
          <p>
            When you upload Solidity smart contracts for analysis, the contract code is processed
            <strong className="text-text-primary"> in memory only</strong> for the duration of the scan.
            Uploaded contracts are:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li><strong className="text-text-primary">Not stored permanently</strong> on our servers</li>
            <li>Processed in-memory during the active scanning session</li>
            <li>Discarded after the analysis is complete and results are returned</li>
            <li>Not used for training any AI models</li>
          </ul>

          <h3 className="text-[13px] font-semibold text-text-primary mt-3 mb-1">2.3 Scan Results</h3>
          <p>
            Audit findings and reports generated by the Service may be temporarily stored to allow you to
            view and download them during your session. These results are associated with your account for
            the duration of your session only.
          </p>
        </section>

        <section>
          <h2 className="text-[15px] font-semibold text-text-primary mb-2">3. How We Use Your Data</h2>
          <p>We use collected information for the following purposes:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>Authenticating your identity and maintaining your session</li>
            <li>Performing security analysis on your uploaded smart contracts</li>
            <li>Generating audit reports and findings</li>
            <li>Improving the Service (aggregated, anonymized usage statistics only)</li>
          </ul>
        </section>

        <section>
          <h2 className="text-[15px] font-semibold text-text-primary mb-2">4. Third-Party Sharing</h2>
          <p>
            We <strong className="text-text-primary">do not sell, rent, or share</strong> your personal
            information or uploaded smart contract code with third parties, except:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>When required by law, regulation, or legal process</li>
            <li>To protect the rights, property, or safety of Alt Research Ltd. or others</li>
          </ul>
        </section>

        <section>
          <h2 className="text-[15px] font-semibold text-text-primary mb-2">5. Google OAuth Data Usage</h2>
          <p>
            Our use of information received from Google APIs adheres to the{' '}
            <a
              href="https://developers.google.com/terms/api-services-user-data-policy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent hover:text-accent-hover transition-colors"
            >
              Google API Services User Data Policy
            </a>
            , including the Limited Use requirements. Specifically:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>We only request the minimum scopes needed (profile and email)</li>
            <li>We do not transfer Google user data to third parties</li>
            <li>We do not use Google user data for advertising</li>
            <li>We do not use Google user data for AI/ML model training</li>
          </ul>
        </section>

        <section>
          <h2 className="text-[15px] font-semibold text-text-primary mb-2">6. Data Security</h2>
          <p>
            We implement reasonable security measures to protect your information, including encrypted
            connections (HTTPS/TLS), secure authentication tokens, and access controls. However, no method
            of electronic transmission or storage is 100% secure, and we cannot guarantee absolute security.
          </p>
        </section>

        <section>
          <h2 className="text-[15px] font-semibold text-text-primary mb-2">7. Data Retention</h2>
          <p>
            Account information is retained for as long as you maintain an account with the Service.
            Uploaded smart contract code is processed in-memory and not retained after analysis. You may
            request deletion of your account and associated data at any time by contacting us.
          </p>
        </section>

        <section>
          <h2 className="text-[15px] font-semibold text-text-primary mb-2">8. Your Rights</h2>
          <p>Depending on your jurisdiction, you may have the right to:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>Access the personal data we hold about you</li>
            <li>Request correction of inaccurate data</li>
            <li>Request deletion of your data</li>
            <li>Withdraw consent for data processing</li>
          </ul>
          <p className="mt-2">
            To exercise these rights, contact us at{' '}
            <a href="mailto:maintainers@altresear.ch" className="text-accent hover:text-accent-hover transition-colors">
              maintainers@altresear.ch
            </a>
          </p>
        </section>

        <section>
          <h2 className="text-[15px] font-semibold text-text-primary mb-2">9. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. Changes will be posted on this page with
            an updated revision date. Your continued use of the Service after changes are posted constitutes
            acceptance of the modified policy.
          </p>
        </section>

        <section>
          <h2 className="text-[15px] font-semibold text-text-primary mb-2">10. Contact</h2>
          <p>
            For privacy-related inquiries, contact us at{' '}
            <a href="mailto:maintainers@altresear.ch" className="text-accent hover:text-accent-hover transition-colors">
              maintainers@altresear.ch
            </a>
          </p>
        </section>

        <div className="pt-4 border-t border-border text-[11px] text-text-secondary">
          Alt Research Ltd. &mdash;{' '}
          <a
            href="https://solidityguard.org"
            target="_blank"
            rel="noopener noreferrer"
            className="text-accent hover:text-accent-hover transition-colors"
          >
            solidityguard.org
          </a>
        </div>
      </div>
    </div>
    </div>
  )
}
